
export default [
  {
    id: 1,
    title: 'Morning Calm',
    description: 'Start your day with a calm mind.',
    duration: '2:14 s',
    category: 'Morning',
    image: ('../assets/images/sunny.webp'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-finding-myself-993.mp3',
  },
  {
    id: 2,
    title: 'Evening Peace',
    description: 'Wind down and relax your body.',
    duration: '2:00 min',
    category: 'Evening',
    image: require('../assets/images/sleep-awake.png'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-harp-relax-669%20(1).mp3',
  },
  {
    id: 3,
    title: 'Focus Booster',
    description: 'Boost your concentration and productivity.',
    duration: '1:04 s',
    category: 'Focus',
    image: require('../assets/images/focus.png'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-nature-meditation-345.mp3',
  },
  {
    id: 4,
    title: 'Sleep Sounds',
    description: 'Drift into sleep with soft ambient sounds.',
    duration: '1:43 s',
    category: 'Sleep',
    image: require('../assets/images/waving.webp'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-lullaby-night-531.mp3',
  },
  
  {
    id: 6,
    title: 'Concentration',
    description: 'Concentrate Better.',
    duration: '1:48 s',
    category: 'Focus',
    image: require('../assets/images/focus.png'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-relax-beat-292.mp3',
  },
  {
    id: 7,
    title: 'Stress Relief',
    description: 'Release tension.',
    duration: '2:45',
    category: 'Relaxation',
    image: require('../assets/images/stressball.png'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-forest-walk-607.mp3',
  },
  {
    id: 8,
    title:'Planting a Seed',
    description: 'Let go of stress and tension.',
    duration: '2:07 s',
    category: 'Uplifting',
    image: require('../assets/images/expert-guide.webp'),
    url: 'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-hazy-after-hours-132.mp3',
  },
  {
    id: 9,
    title: 'Mindful Activity',
    description: 'Let go of stress and tension.',
    duration: '1:49 ',
    category: 'Relaxation',
    image: require('../assets/images/step.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-until-my-last-breath-884.mp3',
  },
  {
    id: 10,
    title: 'The Ancient Power of Mealtime',
    description: '.',
    duration: '2:48 s',
    category: 'Meditation',
    image: require('../assets/images/best.jpg'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-indian-meditations-21.mp3',
  },
  {
    id: 11,
    title: 'Sleepcast',
    description: 'Moonlight Library.',
    duration: '1:50 s',
    category: 'Relaxation',
    image: require('../assets/images/night2.gif'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-dreaming-big-31.mp3',
  },
  {
    id: 12,
    title: 'Inner Awakening',
    description: 'Consistency is Key.',
    duration: '4:54 s',
    category: 'Relaxation',
    image: require('../assets/images/growth.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-fallen-asper-565.mp3',
  },
  {
    id: 13,
    title: 'Standout',
    description: 'Pride From the Inside Out.',
    duration: '2:14 s',
    category: 'Relaxation',
    image: require('../assets/images/smile.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-finding-myself-993.mp3',
  },
  {
    id: 14,
    title: 'Falling asleep',
    description: 'Let go of stress and tension.',
    duration: '2:54 s',
    category: 'Relaxation',
    image: require('../assets/images/night2.gif'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-forest-walk-607.mp3',
  },
  {
    id: 15,
    title: 'Start Your Journey',
    description: 'Let go of stress and tension.',
    duration: '2:00 min',
    category: 'Relaxation',
    image: require('../assets/images/living.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-harp-relax-669%20(1).mp3',
  },
  {
    id: 16,
    title: 'The WakeUp',
    description: 'Wake Up To A New You.',
    duration: '2:07 s',
    category: 'Relaxation',
    image: require('../assets/images/relax.jpg'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-hazy-after-hours-132.mp3',
  },
  {
    id: 17,
    title: 'Go Beyond',
    description: 'Let go of stress and tension.',
    duration: '1:41 s',
    category: 'Relaxation',
    image: require('../assets/images/deep breath.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-island-beat-250.mp3',
  },
  {
    id: 18,
    title: 'Changing Your Perspective',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/changing.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-island-beat-250.mp3',
  },
  {
    id: 19,
    title: 'Relax',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/New.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-lullaby-night-531%20(2).mp3',
  },
  {
    id: 20,
    title: 'Breath',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/Calm.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-music-and-life-852.mp3',
  },
  {
    id: 21,
    title: 'Workout',
    description: 'Let go of stress and tension.',
    duration: '1:43 s',
    category: 'Relaxation',
    image: require('../assets/images/workout.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-nap-time-340.mp3',
  },
  {
    id: 22,
    title: 'Breath',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/Calm.webp'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-nature-meditation-345.mp3',
  },
  {
    id: 23,
    title: 'Rest Assure',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/light.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-ode-to-loneliness-520.mp3',
  },
  {
    id: 24,
    title: 'Ponder About Your Choices',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/ponder.gif'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-pondering-383.mp3',
  },
  {
    id: 25,
    title: 'Body And Mind',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/relax.jpg'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-relax-658.mp3',
  },
  {
    id: 26,
    title: 'Let Go Of Stress And Anxiety',
    description: 'Let go of stress and tension.',
    duration: '1:48 s',
    category: 'Relaxation',
    image: require('../assets/images/grif.png'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-relax-beat-292.mp3',
  },
  {
    id: 27,
    title: 'Breath',
    description: '.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/thumbnail.jpg'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-until-my-last-breath-884.mp3',
  },
  {
    id: 28,
    title: 'Sleep Aid',
    description: 'Let go of stress and tension.',
    duration: '7 min',
    category: 'Relaxation',
    image: require('../assets/images/unnamed.jpg'),
    url:'https://raw.githubusercontent.com/Sumani-Alima-Mahami/SampleTest/refs/heads/main/mixkit-lullaby-night-531%20(2).mp3',
  },
];
